[[main]]
  identifier = "about"
  name = "關於我"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "總覽"
  url = "archive"
  weight = 2

# [[main]]
#   identifier = "categories"
#   name = "分類"
#   url = "categories/"
#   weight = 3

# [[main]]
#   identifier = "gallery"
#   name = "갤러리"
#   url = "gallery"
#   weight = 3
    
# [[main]]
#   parent = "gallery"
#   name = "fiverr"
#   url = "gallery/mine"

# [[main]]
#   identifier = "all posts"
#   name = "全部文章"
#   url = "posts"
#   weight = 4
